"""メトリック定義（企画書 §12-13 の metrics 相当）。

comparison_type:
  absolute          … 差をそのまま（℃, mm, 回, 分 …）
  percentage        … 変化率 (%)
  percentage_point  … ポイント差 (pt)

daily_agg … 同じ日に複数回取得したとき、その日の代表値をどう決めるか
  max / min / last

value_type … number / time(分 since 0:00) / moon(0-29.5)
"""
from __future__ import annotations

METRICS: list[dict] = [
    {
        "slug": "max-temp",
        "name": "全国最高気温",
        "category": "自然",
        "unit": "℃",
        "value_type": "number",
        "comparison_type": "absolute",
        "daily_agg": "max",
        "collector": "jma_rank",
        "source": "気象庁「最新の気象データ」",
        "source_url": "https://www.data.jma.go.jp/stats/data/mdrr/tem_rct/alltable/mxtemsadext00_rct.csv",
    },
    {
        "slug": "min-temp",
        "name": "全国最低気温",
        "category": "自然",
        "unit": "℃",
        "value_type": "number",
        "comparison_type": "absolute",
        "daily_agg": "min",
        "collector": "jma_rank",
        "source": "気象庁「最新の気象データ」",
        "source_url": "https://www.data.jma.go.jp/stats/data/mdrr/tem_rct/alltable/mntemsadext00_rct.csv",
    },
    {
        "slug": "tokyo-max-temp",
        "name": "東京の最高気温",
        "category": "自然",
        "unit": "℃",
        "value_type": "number",
        "comparison_type": "absolute",
        "daily_agg": "max",
        "collector": "jma_rank",
        "station": "44132",  # 東京（大手町→北の丸）
        "source": "気象庁「最新の気象データ」",
        "source_url": "https://www.data.jma.go.jp/stats/data/mdrr/tem_rct/alltable/mxtemsadext00_rct.csv",
    },
    {
        "slug": "max-precip-24h",
        "name": "全国最大24時間降水量",
        "category": "自然",
        "unit": "mm",
        "value_type": "number",
        "comparison_type": "absolute",
        "daily_agg": "max",
        "collector": "jma_rank",
        "source": "気象庁「最新の気象データ」",
        "source_url": "https://www.data.jma.go.jp/stats/data/mdrr/pre_rct/alltable/pre24h00_rct.csv",
    },
    {
        "slug": "hot-points-35",
        "name": "35℃以上になった地点数",
        "category": "自然",
        "unit": "地点",
        "value_type": "number",
        "comparison_type": "absolute",
        "daily_agg": "max",
        "collector": "jma_amedas",
        "source": "気象庁 アメダス実況",
        "source_url": "https://www.jma.go.jp/bosai/amedas/",
    },
    {
        "slug": "hot-points-30",
        "name": "30℃以上になった地点数",
        "category": "自然",
        "unit": "地点",
        "value_type": "number",
        "comparison_type": "absolute",
        "daily_agg": "max",
        "collector": "jma_amedas",
        "source": "気象庁 アメダス実況",
        "source_url": "https://www.jma.go.jp/bosai/amedas/",
    },
    {
        "slug": "cold-points-0",
        "name": "0℃を下回った地点数",
        "category": "自然",
        "unit": "地点",
        "value_type": "number",
        "comparison_type": "absolute",
        "daily_agg": "max",
        "collector": "jma_amedas",
        "source": "気象庁 アメダス実況",
        "source_url": "https://www.jma.go.jp/bosai/amedas/",
    },
    {
        "slug": "rain-points",
        "name": "雨が降った地点数",
        "category": "自然",
        "unit": "地点",
        "value_type": "number",
        "comparison_type": "absolute",
        "daily_agg": "max",
        "collector": "jma_amedas",
        "source": "気象庁 アメダス実況",
        "source_url": "https://www.jma.go.jp/bosai/amedas/",
    },
    {
        "slug": "max-precip-1h",
        "name": "全国最大1時間降水量",
        "category": "自然",
        "unit": "mm",
        "value_type": "number",
        "comparison_type": "absolute",
        "daily_agg": "max",
        "collector": "jma_amedas",
        "source": "気象庁 アメダス実況",
        "source_url": "https://www.jma.go.jp/bosai/amedas/",
    },
    {
        "slug": "max-precip-3h",
        "name": "全国最大3時間降水量",
        "category": "自然",
        "unit": "mm",
        "value_type": "number",
        "comparison_type": "absolute",
        "daily_agg": "max",
        "collector": "jma_amedas",
        "source": "気象庁 アメダス実況",
        "source_url": "https://www.jma.go.jp/bosai/amedas/",
    },
    {
        "slug": "national-temp-spread",
        "name": "全国の気温差（最も暑い地点と寒い地点）",
        "category": "自然",
        "unit": "℃",
        "value_type": "number",
        "comparison_type": "absolute",
        "daily_agg": "max",
        "collector": "jma_amedas",
        "source": "気象庁 アメダス実況",
        "source_url": "https://www.jma.go.jp/bosai/amedas/",
    },
    {
        "slug": "tokyo-forecast-max",
        "name": "東京のあしたの最高気温",
        "category": "自然",
        "unit": "℃",
        "value_type": "number",
        "comparison_type": "absolute",
        "daily_agg": "last",
        "collector": "jma_forecast",
        "source": "気象庁 天気予報",
        "source_url": "https://www.jma.go.jp/bosai/forecast/data/forecast/130000.json",
    },
    {
        "slug": "tokyo-forecast-min",
        "name": "東京のあしたの最低気温",
        "category": "自然",
        "unit": "℃",
        "value_type": "number",
        "comparison_type": "absolute",
        "daily_agg": "last",
        "collector": "jma_forecast",
        "source": "気象庁 天気予報",
        "source_url": "https://www.jma.go.jp/bosai/forecast/data/forecast/130000.json",
    },
    {
        "slug": "tokyo-forecast-pop",
        "name": "東京のあしたの降水確率",
        "category": "自然",
        "unit": "%",
        "value_type": "number",
        "comparison_type": "percentage_point",
        "daily_agg": "last",
        "collector": "jma_forecast",
        "source": "気象庁 天気予報",
        "source_url": "https://www.jma.go.jp/bosai/forecast/data/forecast/130000.json",
    },
    {
        "slug": "min-pressure",
        "name": "全国の最低海面気圧",
        "category": "自然",
        "unit": "hPa",
        "value_type": "number",
        "comparison_type": "absolute",
        "daily_agg": "min",
        "collector": "jma_amedas",
        "source": "気象庁 アメダス実況",
        "source_url": "https://www.jma.go.jp/bosai/amedas/",
    },
    {
        "slug": "max-wind",
        "name": "全国最大風速（10分平均）",
        "category": "自然",
        "unit": "m/s",
        "value_type": "number",
        "comparison_type": "absolute",
        "daily_agg": "max",
        "collector": "jma_amedas",
        "source": "気象庁 アメダス実況",
        "source_url": "https://www.jma.go.jp/bosai/amedas/",
    },
    {
        "slug": "min-humidity",
        "name": "全国の最小湿度",
        "category": "自然",
        "unit": "%",
        "value_type": "number",
        "comparison_type": "percentage_point",
        "daily_agg": "min",
        "collector": "jma_amedas",
        "source": "気象庁 アメダス実況",
        "source_url": "https://www.jma.go.jp/bosai/amedas/",
    },
    {
        "slug": "snow-points",
        "name": "雪が積もっている地点数",
        "category": "自然",
        "unit": "地点",
        "value_type": "number",
        "comparison_type": "absolute",
        "daily_agg": "max",
        "collector": "jma_amedas",
        "source": "気象庁 アメダス実況",
        "source_url": "https://www.jma.go.jp/bosai/amedas/",
    },
    {
        "slug": "max-snow",
        "name": "全国最深積雪",
        "category": "自然",
        "unit": "cm",
        "value_type": "number",
        "comparison_type": "absolute",
        "daily_agg": "max",
        "collector": "jma_amedas",
        "source": "気象庁 アメダス実況",
        "source_url": "https://www.jma.go.jp/bosai/amedas/",
    },
    {
        "slug": "fuji-temp",
        "name": "富士山頂の気温",
        "category": "自然",
        "unit": "℃",
        "value_type": "number",
        "comparison_type": "absolute",
        "daily_agg": "last",
        "collector": "jma_amedas",
        "source": "気象庁 アメダス実況（富士山）",
        "source_url": "https://www.jma.go.jp/bosai/amedas/",
    },
    {
        "slug": "days-to-sekki",
        "name": "次の二十四節気まで",
        "category": "こよみ",
        "unit": "日",
        "value_type": "number",
        "comparison_type": "absolute",
        "trend": "countdown",
        "daily_agg": "last",
        "collector": "astro",
        "source": "自前天文計算",
        "source_url": "https://eco.mtk.nao.ac.jp/koyomi/",
    },
    {
        "slug": "gas-regular",
        "name": "レギュラーガソリンの全国平均価格",
        "category": "経済",
        "unit": "円/L",
        "value_type": "number",
        "comparison_type": "absolute",
        "daily_agg": "last",
        "collector": "enecho_gas",
        "source": "資源エネルギー庁 石油製品価格調査",
        "source_url": "https://www.enecho.meti.go.jp/statistics/petroleum_and_lpgas/pl007/results.html",
    },
    {
        "slug": "usd-jpy",
        "name": "ドル円レート",
        "category": "経済",
        "unit": "円",
        "value_type": "number",
        "comparison_type": "absolute",
        "daily_agg": "last",
        "collector": "boj_fx",
        "source": "日本銀行 時系列統計データ（東京市場・17時時点）",
        "source_url": "https://www.stat-search.boj.or.jp/ssi/mtshtml/csv/fm08_d_1.csv",
    },
    {
        "slug": "typhoons-this-year",
        "name": "今年の台風発生数",
        "category": "防災",
        "unit": "個",
        "value_type": "number",
        "comparison_type": "absolute",
        "daily_agg": "max",
        "collector": "jma_typhoon",
        "source": "気象庁 台風情報",
        "source_url": "https://www.jma.go.jp/bosai/typhoon/data/targetTc.json",
    },
    {
        "slug": "active-typhoons",
        "name": "発生中の台風の数",
        "category": "防災",
        "unit": "個",
        "value_type": "number",
        "comparison_type": "absolute",
        "daily_agg": "last",
        "collector": "jma_typhoon",
        "source": "気象庁 台風情報",
        "source_url": "https://www.jma.go.jp/bosai/typhoon/data/targetTc.json",
    },
    {
        "slug": "warned-municipalities",
        "name": "気象警報が出ている市町村数",
        "category": "防災",
        "unit": "市町村",
        "value_type": "number",
        "comparison_type": "absolute",
        "daily_agg": "last",
        "collector": "jma_warning",
        "source": "気象庁 気象警報・注意報",
        "source_url": "https://www.jma.go.jp/bosai/warning/data/r8/map.json",
    },
    {
        "slug": "day-length-tokyo",
        "name": "東京の昼の長さ",
        "category": "こよみ",
        "unit": "",
        "value_type": "duration",
        "comparison_type": "absolute",
        "daily_agg": "last",
        "collector": "astro",
        "source": "自前天文計算",
        "source_url": "https://eco.mtk.nao.ac.jp/koyomi/",
    },
    {
        "slug": "days-left-year",
        "name": "今年の残り日数",
        "category": "こよみ",
        "unit": "日",
        "value_type": "number",
        "comparison_type": "absolute",
        "trend": "countdown",
        "daily_agg": "last",
        "collector": "astro",
        "source": "計算のみ",
        "source_url": "",
    },
    {
        "slug": "moonrise-tokyo",
        "name": "東京の月の出",
        "category": "こよみ",
        "unit": "",
        "value_type": "time",
        "comparison_type": "absolute",
        "daily_agg": "last",
        "collector": "astro",
        "source": "自前天文計算",
        "source_url": "https://eco.mtk.nao.ac.jp/koyomi/",
    },
    {
        "slug": "moonset-tokyo",
        "name": "東京の月の入り",
        "category": "こよみ",
        "unit": "",
        "value_type": "time",
        "comparison_type": "absolute",
        "daily_agg": "last",
        "collector": "astro",
        "source": "自前天文計算",
        "source_url": "https://eco.mtk.nao.ac.jp/koyomi/",
    },
    {
        "slug": "days-to-full-moon",
        "name": "次の満月まで",
        "category": "こよみ",
        "unit": "日",
        "value_type": "number",
        "comparison_type": "absolute",
        "trend": "countdown",
        "daily_agg": "last",
        "collector": "astro",
        "source": "自前天文計算",
        "source_url": "https://eco.mtk.nao.ac.jp/koyomi/",
    },
    {
        "slug": "biwako-level",
        "name": "琵琶湖の水位",
        "category": "自然",
        "unit": "cm",
        "value_type": "number",
        "comparison_type": "absolute",
        "daily_agg": "last",
        "collector": "mlit_water",
        "source": "国土交通省 近畿地方整備局",
        "source_url": "https://www.kkr.mlit.go.jp/river/json/dam.json",
    },
    {
        "slug": "dam-storage",
        "name": "主要ダムの貯水率",
        "category": "自然",
        "unit": "%",
        "value_type": "number",
        "comparison_type": "percentage_point",
        "daily_agg": "last",
        "collector": "mlit_water",
        "source": "国土交通省 近畿・関東地方整備局",
        "source_url": "https://www.kkr.mlit.go.jp/river/json/dam.json",
    },
    {
        "slug": "elec-usage-tokyo",
        "name": "東京エリアの電力使用率",
        "category": "インフラ",
        "unit": "%",
        "value_type": "number",
        "comparison_type": "percentage_point",
        "daily_agg": "last",
        "collector": "tepco_pg",
        "source": "東京電力パワーグリッド でんき予報",
        "source_url": "https://www.tepco.co.jp/forecast/html/images/juyo-s1-j.csv",
    },
    {
        "slug": "solar-share-tokyo",
        "name": "東京エリアの太陽光発電シェア（ピーク）",
        "category": "インフラ",
        "unit": "%",
        "value_type": "number",
        "comparison_type": "percentage_point",
        "daily_agg": "max",
        "collector": "tepco_pg",
        "source": "東京電力パワーグリッド でんき予報",
        "source_url": "https://www.tepco.co.jp/forecast/html/images/juyo-s1-j.csv",
    },
    {
        "slug": "quakes-24h",
        "name": "地震回数（過去24時間・震度1以上）",
        "category": "防災",
        "unit": "回",
        "value_type": "number",
        "comparison_type": "absolute",
        "daily_agg": "last",
        "collector": "p2pquake",
        "source": "P2P地震情報 API（元データ：気象庁）",
        "source_url": "https://api.p2pquake.net/v2/history?codes=551",
    },
    {
        "slug": "max-shindo-7d",
        "name": "この1週間の最大震度",
        "category": "防災",
        "unit": "",
        "value_type": "shindo",
        "comparison_type": "absolute",
        "daily_agg": "max",
        "collector": "p2pquake",
        "source": "P2P地震情報 API（元データ：気象庁）",
        "source_url": "https://api.p2pquake.net/v2/history?codes=551",
    },
    {
        "slug": "sunset-tokyo",
        "name": "東京の日の入り時刻",
        "category": "こよみ",
        "unit": "",
        "value_type": "time",
        "comparison_type": "absolute",
        "daily_agg": "last",
        "collector": "astro",
        "source": "自前天文計算（NOAA式）",
        "source_url": "https://eco.mtk.nao.ac.jp/koyomi/",
    },
    {
        "slug": "sunrise-tokyo",
        "name": "東京の日の出時刻",
        "category": "こよみ",
        "unit": "",
        "value_type": "time",
        "comparison_type": "absolute",
        "daily_agg": "last",
        "collector": "astro",
        "source": "自前天文計算（NOAA式）",
        "source_url": "https://eco.mtk.nao.ac.jp/koyomi/",
    },
    {
        "slug": "moon-age",
        "name": "月齢",
        "category": "こよみ",
        "unit": "",
        "value_type": "moon",
        "comparison_type": "absolute",
        "daily_agg": "last",
        "collector": "astro",
        "source": "自前天文計算",
        "source_url": "https://eco.mtk.nao.ac.jp/koyomi/",
    },
]

BY_SLUG: dict[str, dict] = {m["slug"]: m for m in METRICS}


def metrics_for(collector: str) -> list[dict]:
    return [m for m in METRICS if m["collector"] == collector]
